//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by an Xomega.Net generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
define(["require", "exports"], function (require, exports) {
    "use strict";
    var Cars_ReadOutput = (function () {
        function Cars_ReadOutput() {
            this.Name = null;
            this.Quantity = null;
            this.Type = null;
        }
        return Cars_ReadOutput;
    }());
    exports.Cars_ReadOutput = Cars_ReadOutput;
    var Cars_CreateInput = (function () {
        function Cars_CreateInput() {
            this.Name = null;
            this.Quantity = null;
            this.Type = null;
        }
        return Cars_CreateInput;
    }());
    exports.Cars_CreateInput = Cars_CreateInput;
    var Cars_CreateOutput = (function () {
        function Cars_CreateOutput() {
            this.Id = null;
        }
        return Cars_CreateOutput;
    }());
    exports.Cars_CreateOutput = Cars_CreateOutput;
    var Cars_UpdateInput_Data = (function () {
        function Cars_UpdateInput_Data() {
            this.Name = null;
            this.Quantity = null;
            this.Type = null;
        }
        return Cars_UpdateInput_Data;
    }());
    exports.Cars_UpdateInput_Data = Cars_UpdateInput_Data;
    var Cars_ReadListInput_Criteria = (function () {
        function Cars_ReadListInput_Criteria() {
            this.NameOperator = null;
            this.Name = null;
            this.QuantityOperator = null;
            this.Quantity = null;
            this.Quantity2 = null;
            this.TypeOperator = null;
            this.Type = null;
        }
        return Cars_ReadListInput_Criteria;
    }());
    exports.Cars_ReadListInput_Criteria = Cars_ReadListInput_Criteria;
    var Cars_ReadListOutput = (function () {
        function Cars_ReadListOutput() {
            this.Id = null;
            this.Name = null;
            this.Quantity = null;
            this.Type = null;
        }
        return Cars_ReadListOutput;
    }());
    exports.Cars_ReadListOutput = Cars_ReadListOutput;
});
//# sourceMappingURL=_Cars.js.map