//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by an Xomega.Net generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


export class Cars_ReadOutput
{
    public Name : any = null;
    public Quantity : any = null;
    public Type : any = null;
}

export class Cars_CreateInput
{
    public Name : any = null;
    public Quantity : any = null;
    public Type : any = null;
}

export class Cars_CreateOutput
{
    public Id : any = null;
}

export class Cars_UpdateInput_Data
{
    public Name : any = null;
    public Quantity : any = null;
    public Type : any = null;
}

export class Cars_ReadListInput_Criteria
{
    public NameOperator : any = null;
    public Name : any = null;
    public QuantityOperator : any = null;
    public Quantity : any = null;
    public Quantity2 : any = null;
    public TypeOperator : any = null;
    public Type : any = null;
}

export class Cars_ReadListOutput
{
    public Id : any = null;
    public Name : any = null;
    public Quantity : any = null;
    public Type : any = null;
}
