//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by an Xomega.Net generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
define(["require", "exports", "xomega"], function (require, exports, xomega) {
    "use strict";
    var CarsObject = (function (_super) {
        __extends(CarsObject, _super);
        function CarsObject() {
            _super.apply(this, arguments);
        }
        // Construction and initialization
        CarsObject.prototype.init = function () {
            this.Id = new xomega.IntegerProperty();
            this.Id.Required(true);
            this.Name = new xomega.TextProperty();
            this.Name.Size = 50;
            this.Quantity = new xomega.DecimalProperty();
            this.Type = new xomega.TextProperty();
            this.Type.Size = 50;
        };
        return CarsObject;
    }(xomega.DataObject));
    exports.CarsObject = CarsObject;
});
//# sourceMappingURL=_DOCarsObject.js.map