//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by an Xomega.Net generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import xomega = require("xomega");

export class CarsObject extends xomega.DataObject
{
    // Properties
    public Id: xomega.IntegerProperty;
    public Name: xomega.TextProperty;
    public Quantity: xomega.DecimalProperty;
    public Type: xomega.TextProperty;

    // Construction and initialization
    init()
    {
        this.Id = new xomega.IntegerProperty();
        this.Id.Required(true);
        this.Name = new xomega.TextProperty();
        this.Name.Size = 50;
        this.Quantity = new xomega.DecimalProperty();
        this.Type = new xomega.TextProperty();
        this.Type.Size = 50;
    }
}
