//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by an Xomega.Net generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated constants for all enumerations as classes with the enumeration name 
// stored in a special field EnumName and other items declared as static fields.
// Additional attributes are declared inside "nested" classes Attributes.
export module Enumerations
{
    export class Operators
    {
        public static EnumName: string = "operators";

        public static IsNull: string = "NULL";
        public static IsNotNull: string = "NOTNULL";
        public static IsEqualTo: string = "IS";
        public static IsNotEqualTo: string = "ISNOT";
        public static IsOneOf: string = "ONEOF";
        public static IsNoneOf: string = "NONEOF";
        public static IsLessThan: string = "LESS";
        public static IsNotLessThan: string = "NOTLESS";
        public static IsGreaterThan: string = "GREATER";
        public static IsNotGreaterThan: string = "NOTGREATER";
        public static IsEarlierThan: string = "EARLIER";
        public static IsLaterThan: string = "LATER";
        public static IsBetween: string = "BETWEEN";
        public static Contains: string = "CONT";
        public static DoesNotContain: string = "NOTCONT";
    }
    export module Operators
    {
        export class Attributes
        {
            public static SortOrder: string = "sort order";
            public static AddlProps: string = "addl props";
            public static Multival: string = "multival";
            public static Type: string = "type";
            public static ExcludeType: string = "exclude type";
            public static NullCheck: string = "null check";
        }
    }

    export class Yesno
    {
        public static EnumName: string = "yesno";

        public static Yes: string = "true";
        public static No: string = "false";
    }
}
