//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testt
    {
        public int Id { get; set; }
        public Nullable<int> Test1 { get; set; }
        public string Test2 { get; set; }
    }
}
