//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by an Xomega.Net generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Web;
using Xomega.Framework;

namespace MyProject2.Services
{
    #region ICarsService

    [ServiceContract]
    public interface ICarsService
    {

        ///<summary>
        /// Reads the values of a Cars object by its key.
        ///</summary>
        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        [WebGet(UriTemplate="cars/{_id}")]
        Cars_ReadOutput Read(int _id);

        ///<summary>
        /// Creates a new Cars object using the specified data.
        ///</summary>
        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        [WebInvoke(UriTemplate="cars")]
        Cars_CreateOutput Create(Cars_CreateInput _data);

        ///<summary>
        /// Updates existing Cars object using the specified data.
        ///</summary>
        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        [WebInvoke(Method="PUT", UriTemplate="cars/{_id}")]
        void Update(int _id, Cars_UpdateInput_Data _data);

        ///<summary>
        /// Deletes the specified Cars object.
        ///</summary>
        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        [WebInvoke(Method="DELETE", UriTemplate="cars/{_id}")]
        void Delete(int _id);

        ///<summary>
        /// Reads a list of Cars objects based on the specified criteria.
        ///</summary>
        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        [WebGet(UriTemplate="cars?{_criteria}")]
        IEnumerable<Cars_ReadListOutput> ReadList(Cars_ReadListInput_Criteria _criteria);

    }
    #endregion

    #region Cars_ReadOutput structure

    ///<summary>
    /// The output structure of operation ICarsService.Read.
    ///</summary>
    [DataContract]
    public class Cars_ReadOutput
    {
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public decimal? Quantity { get; set; }
        [DataMember]
        public string Type { get; set; }
    }
    #endregion

    #region Cars_CreateInput structure

    ///<summary>
    /// The input structure of operation ICarsService.Create.
    ///</summary>
    [DataContract]
    public class Cars_CreateInput
    {
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public decimal? Quantity { get; set; }
        [DataMember]
        public string Type { get; set; }
    }
    #endregion

    #region Cars_CreateOutput structure

    ///<summary>
    /// The output structure of operation ICarsService.Create.
    ///</summary>
    [DataContract]
    public class Cars_CreateOutput
    {
        [DataMember]
        public int Id { get; set; }
    }
    #endregion

    #region Cars_UpdateInput_Data structure

    ///<summary>
    /// Structure of parameter Data of the input structure of operation ICarsService.Update.
    ///</summary>
    [DataContract]
    public class Cars_UpdateInput_Data
    {
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public decimal? Quantity { get; set; }
        [DataMember]
        public string Type { get; set; }
    }
    #endregion

    #region Cars_ReadListInput_Criteria structure

    ///<summary>
    /// Structure of parameter Criteria of the input structure of operation ICarsService.ReadList.
    ///</summary>
    [DataContract]
    public class Cars_ReadListInput_Criteria
    {
        ///<summary>
        /// Comparison operator for the corresponding Name criteria.
        ///</summary>
        [DataMember]
        public string NameOperator { get; set; }
        [DataMember]
        public string Name { get; set; }
        ///<summary>
        /// Comparison operator for the corresponding Quantity criteria.
        ///</summary>
        [DataMember]
        public string QuantityOperator { get; set; }
        [DataMember]
        public decimal? Quantity { get; set; }
        ///<summary>
        /// End of range for the corresponding Quantity criteria for the BETWEEN operator.
        ///</summary>
        [DataMember]
        public decimal? Quantity2 { get; set; }
        ///<summary>
        /// Comparison operator for the corresponding Type criteria.
        ///</summary>
        [DataMember]
        public string TypeOperator { get; set; }
        [DataMember]
        public string Type { get; set; }
    }
    #endregion

    #region Cars_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ICarsService.ReadList.
    ///</summary>
    [DataContract]
    public class Cars_ReadListOutput
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public decimal? Quantity { get; set; }
        [DataMember]
        public string Type { get; set; }
    }
    #endregion

}